version: '3.8'

services:
  virtual-gallery:
    build: .
    ports:
      - "3000:3000"
    volumes:
      # Монтируем папки для сохранения данных
      - ./public/models:/app/public/models
      - ./public/images:/app/public/images
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - NODE_ENV=production


